lqr:
  N: 60
  dt: 0.1
  nx: 4
  nu: 2
  w_pos: 1.0
  w_vel: 0.5
  w_acc: 1.0
  w_stl: 1.0
  exp_q1: 5.5
  exp_q2: 2.75

iteration:
  max_iter: 500
  init_lamb: 20
  lamb_decay: 0.7
  lamb_amplify: 2.0
  max_lamb: 10000.0
  alpha_options: [1., 0.5, 0.25, 0.125, 0.0625, 0.03125, 0.015625 , 0.0078125]
  tol: 0.0005

vehicle:
  wheelbase: 3.6
  width: 2
  length: 4.5
  velo_max: 10.0
  velo_min: 0.0
  yaw_lim: 3.14
  acc_max: 2.0
  acc_min: -2.0
  stl_lim: 1.57

laneline:
  reference:
    x: [0, 10, 20, 35, 70]
    y: [1, 0, 5, 6.5, 0]
  border: [-1.8, 1.8, 5.4, 9]
  center_line: [3.6, 7.2]
