max_simulation_time: 12
delta_t: 0.1

lqr:
  N: 30
  nx: 4
  nu: 2
  w_pos: 1.0
  w_vel: 1.0
  w_acc: 0.5
  w_stl: 15.0
  obstacle_exp_q1: 5.5
  obstacle_exp_q2: 5.75
  state_exp_q1: 3.0
  state_exp_q2: 2.5
  use_last_solution: false

iteration:
  max_iter: 120
  init_lamb: 20
  lamb_decay: 0.7
  lamb_amplify: 2.0
  max_lamb: 10000.0
  tol: 0.00001

vehicle:
  target_velocity: 8
  wheelbase: 3.6
  width: 2
  length: 4.5
  velo_max: 15.0
  velo_min: 0.0
  yaw_lim: 3.14
  acc_max: 3.0
  acc_min: -3.0
  stl_lim: 1.58
  d_safe: 1.8

laneline:
  reference:
    x: [-10, 0, 50, 100, 150, 200]
    y: [0, 0, 0, 0, 0, 0]
  border: [-1.8, 1.8, 5.4]
  center_line: [0, 3.6]

initial_condition:
  # [x, y, v, yaw]
  - [0, 0, 6.0, 0]  # ego
  - [30, 0, 3.0, 0]
  - [30, 3.6, 5, 0]
  - [15, 3.6, 3.0, 0]

visualization:
  y_lim: [-5, 13]
